## Numpy Study Notes

In [23]:
#import numpy liberary as np by convention
import numpy as np

In [4]:
#creating numpy array from existing list
my_list = [1,2,3,4]
#using np.array() method
np_array = np.array(my_list)
np_array

array([1, 2, 3, 4])

In [7]:
#create an array of numbers using np.arange()
#np.arange(start, end, step) note. end is not inclusive
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
#Creating array of zeros
#if the shape arg is one number the array will be one dimensional
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
#Creating an array of ones, the same as the above
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
#create an array of equally spaced numbers
#np.linspace(start, end, num) note. end is inclusive
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [22]:
#Creating an identity matrix
#np.identity(num) the num is the number of rows and cols
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
#return an arry of 5 random numbers between 0 and 1
np.random.rand(5)

#return an array of 5x5 matrix from 0 to 1, note that 1 is exclusive
np.random.rand(5,5)

array([[0.41829973, 0.02668107, 0.22291604, 0.87980545, 0.69406505],
       [0.33766538, 0.90946104, 0.39441915, 0.53622326, 0.17877515],
       [0.15086948, 0.79194297, 0.97122643, 0.85364114, 0.41408119],
       [0.04351186, 0.84235276, 0.81625638, 0.31967256, 0.13104638],
       [0.36146133, 0.02213632, 0.21994782, 0.00129089, 0.85876163]])

In [33]:
# the same but numbers near zero are most likely picked
np.random.randn(5, 5)
#Note that the above two methods can be used to get number of random values or an array of shape

array([[-0.24268294, -0.49986011, -0.74093573, -0.20297844,  1.02602948],
       [-1.51757325, -1.04938359, -0.43508158, -1.13620379, -0.91857311],
       [ 0.07129443,  0.15018701,  2.5712639 ,  0.28875828, -0.47511277],
       [-0.94280625,  0.61896558, -0.51788798, -0.08288136,  1.90516705],
       [-1.14696001,  0.41615729, -0.96570673,  0.83654607,  0.24933645]])

In [39]:
#used to get an integer value between start(inclusive) and end(exclusive)
np.random.randint(0, 10)

#can also be used to create an array of random integers
#np.random.randint(start, end, (shape or size))
np.random.randint(0, 10, (5,5))

array([[3, 1, 8, 6, 3],
       [6, 1, 5, 8, 6],
       [5, 2, 3, 0, 2],
       [6, 2, 8, 2, 2],
       [1, 3, 4, 2, 9]])

In [44]:
#Notice that every time you run the any random method you get different results
#The solution to this is by setting a seed to get the same particlur set of nums
np.random.seed(42)#the seed number can be anything

#then in the same cell try to get some random values
np.random.randint(0,10, 5)# every time you run the cell you get the same set of numbers 

array([6, 3, 7, 4, 6])

In [48]:
arr = np.random.rand(5, 4)
arr

array([[0.42340148, 0.39488152, 0.29348817, 0.01407982],
       [0.1988424 , 0.71134195, 0.79017554, 0.60595997],
       [0.92630088, 0.65107703, 0.91495968, 0.85003858],
       [0.44945067, 0.09541012, 0.37081825, 0.66884125],
       [0.66592236, 0.59129779, 0.27472179, 0.56124343]])

In [55]:
#You can use reshape method to reshape the dimensions of an array
arr2 = np.arange(0,20)
arr2.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [57]:
#but notice that you cant reshape an array of 5x4 to 5x5 etc
arr.reshape(5,5)#You get an error

ValueError: cannot reshape array of size 20 into shape (5,5)

In [59]:
#Max and min of an array
arr.max()
arr.min()

0.014079822715084456

In [61]:
#index of max and min 
arr.argmax()
arr.argmin()

3

In [65]:
#return the shape of an array
arr.shape

(5, 4)